"""add neighborhood column to citizens

Revision ID: bd5026cd32f7
Revises: 2cdfcfa31200
Create Date: 2026-08-14 03:17:31.755763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd5026cd32f7'
down_revision: Union[str, None] = '2cdfcfa31200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizens', sa.Column('neighborhood', sa.String(length=50), nullable=False))
    op.add_column('comments', sa.Column('parent_comment_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_comments_parent_comment_id'), 'comments', ['parent_comment_id'], unique=False)
    op.create_foreign_key(None, 'comments', 'comments', ['parent_comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_comments_parent_comment_id'), table_name='comments')
    op.drop_column('comments', 'parent_comment_id')
    op.drop_column('citizens', 'neighborhood')
    # ### end Alembic commands ###
