"""create timeline_events table

Revision ID: e6c75f9ec5e1
Revises: 092a90e159c9
Create Date: 2026-08-08 16:36:29.938466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c75f9ec5e1'
down_revision: Union[str, None] = '092a90e159c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tick_number', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_category'), 'timeline_events', ['category'], unique=False)
    op.create_index(op.f('ix_timeline_events_created_at'), 'timeline_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_timeline_events_tick_number'), 'timeline_events', ['tick_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_events_tick_number'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_created_at'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_category'), table_name='timeline_events')
    op.drop_table('timeline_events')
    # ### end Alembic commands ###
