"""create governments table

The Government / President / First Lady system. Purely ADDITIVE — creates one
new table and alters nothing that already exists.

WHY ONLY ONE TABLE
------------------
Office holders are citizens, so the table stores citizen ids and the names are
resolved by join at request time. That is what makes renaming a citizen rename
the President on the 3D map with no regeneration and no frontend change. Copied
name strings would go stale, the same reason there is no cached `population` on
`cities` and no cached `money` on `citizens`.

There is deliberately NO `capital_city_id` column: `cities.is_capital` already
records the seat of government, and a second copy could disagree with the world
data the map is drawn from.

FK delete behaviour, and why:
  governments.president_citizen_id  -> SET NULL (deleting a citizen vacates the
                                                 office; it must never cascade
                                                 into deleting the government)
  governments.first_lady_citizen_id -> SET NULL (same)

NOT created here, on purpose (spec §21 lists these as future work): elections,
parliament membership, ministers, a terms table, or marriages. The Parliament
*building* is already generated by World Phase 2 and needs nothing from this
migration.

Revision ID: f18a3c6d40b2
Revises: c3d8e5a91b47
Create Date: 2026-08-21 13:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f18a3c6d40b2'
down_revision: Union[str, None] = 'c3d8e5a91b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'governments',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('president_citizen_id', sa.Integer(), nullable=True),
        sa.Column('first_lady_citizen_id', sa.Integer(), nullable=True),
        # 0.0-1.0 fraction, not a percentage — see models/government.py.
        sa.Column('tax_rate', sa.Float(), nullable=False, server_default=sa.text('0.10')),
        sa.Column(
            'curfew_enabled', sa.Boolean(), nullable=False, server_default=sa.text('0')
        ),
        sa.Column(
            'term_started_tick', sa.Integer(), nullable=False, server_default=sa.text('0')
        ),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(
            ['president_citizen_id'], ['citizens.id'],
            name='fk_governments_president_citizen_id',
            ondelete='SET NULL',
        ),
        sa.ForeignKeyConstraint(
            ['first_lady_citizen_id'], ['citizens.id'],
            name='fk_governments_first_lady_citizen_id',
            ondelete='SET NULL',
        ),
    )
    op.create_index(
        op.f('ix_governments_president_citizen_id'),
        'governments',
        ['president_citizen_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_governments_first_lady_citizen_id'),
        'governments',
        ['first_lady_citizen_id'],
        unique=False,
    )


def downgrade() -> None:
    # Exact reverse order. Both constraints above are explicitly named so MySQL
    # can drop them by name instead of relying on auto-generated identifiers.
    op.drop_index(op.f('ix_governments_first_lady_citizen_id'), table_name='governments')
    op.drop_index(op.f('ix_governments_president_citizen_id'), table_name='governments')
    op.drop_table('governments')
